### ISSUE TITLE
Download counter has been broken since April 19th

### ISSUE THREAD

**Issue by AuroraLS3** [windy1/Pore#998] opened 2020-06-28 18:04 UTC
**Describe the bug**

All download counters for plugin versions uploaded after April 19th are 0. 

This suggests that the commits on April 19 broke download counter from going up when a download occurs.

1. I looked at multiple plugins and could not find a single one with downloads after April 19th.
2. https://ore.spongepowered.org/?sort=newest New plugins uploaded after April 19th have no downloads.

**To Reproduce**
1. This might need checking from the database, but it seems clear from the page.

**Expected behavior**
Plugin downloads should count up when they are downloaded.

**Screenshots**

From versions of a couple plugins

![image](https://user-images.githubusercontent.com/24460436/85954622-887c7900-b981-11ea-9386-4cc501e624f4.png)
----
![image](https://user-images.githubusercontent.com/24460436/85954630-94683b00-b981-11ea-911f-2106b229aabc.png)
Plugins that were added (new) after April 19th
![image](https://user-images.githubusercontent.com/24460436/85954649-b497fa00-b981-11ea-9082-9e3778d536b0.png)

**Environment**
 - Windows 10
 - Firefox 77.0.1

**Additional context**

[Jump to: Commits April 19](https://github.com/SpongePowered/Ore/commits/staging?before=8305d6ed4e52c0cb2021952cefc60412ef1f57a6+44)

**Comment by Katrix** [comment] 2020-06-28 18:05
Duplicate of #993

**Closed as completed by Katrix** 2020-06-28 18:05 UTC
Labels: status: needs testing, type: bug report, environment: production
