### ISSUE TITLE
API Responses Differ

### ISSUE THREAD

**Issue by darbyjack** [windy1/Pore#1056] opened 2022-02-17 20:37 UTC
**Describe the bug**

API response permissions are not being created properly.

**To Reproduce**

1) Create an auth instance with an API key
2) Take the session ID and send a request to the URL in the description above (LuckPerms), check the permission response output.

It will look like this **when using a session created via an auth key** (the key has view_public_info checked)
```JSON
{
    "type": "project",
    "permissions": []
}
```

When you use a session created **without an auth key**, it will look like this:
```JSON
{
    "type": "project",
    "permissions": [
        "view_public_info"
    ]
}
```

**Expected behavior**

Apikey sessions to have the `view_public_info` when selected during creation.

**Screenshots**

![image](https://user-images.githubusercontent.com/21014720/154566591-66be14e7-2762-4724-93bf-996470202934.png)

**Environment **
 - Windows 10

**Additional context**

**Comment by Katrix** [comment] 2023-10-17 10:36
Can't reproduce with latest commit. Might have been fixed in a refactoring

**Closed as completed by Katrix** 2023-10-17 10:36 UTC
Labels: status: needs testing, api version: 2, type: bug report, environment: production
