### ISSUE TITLE
Broken Ore links in Discourse posts

### ISSUE THREAD

**Issue by randombyte-developer** [windy1/Pore#932] opened 2019-10-24 13:29 UTC
The link to Ore in the automatic posts on Discourse are broken.

For example in this post: https://forums.spongepowered.org/t/magibridge-a-utility-discord-minecraft-chat-relay-plugin/19796/55?u=randombyte

**Comment by Katrix** [comment] 2019-10-24 13:30
Duplicate of #912

**Closed as completed by Katrix** 2019-10-24 13:30 UTC
Labels: resolution: duplicate
